name: CI

on:
  - push

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.11.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - run: opam pin add skapm.dev -n .
      - run: opam depext -yt skapm
      - run: opam install -t . --deps-only
      - run: opam exec -- dune build

